🔀 :: (#8) 로그인 실패 알림 구현
Team-OnePiece/OnePiece_iOS pull request #9
Opened 2023-07-26 12:23 UTC by cyj513

close #8

2023-07-26 14:41 UTC, juyeong525 requested changes

2023-07-26 14:41 UTC, juyeong525 commented on OnePiece/OnePiece/Scene/Auth/Login/LoginViewController.swift
> +        if (idTextField.text?.isEmpty == true || passwordTextField.text?.isEmpty == true) {
bool 값일 경우에는 굳이 == true 안써줘도 됩니다

2023-07-26 14:41 UTC, juyeong525 commented on OnePiece/OnePiece/Scene/Auth/Login/LoginViewController.swift
> +//        self.navigationController?.pushViewController(MainViewController(), animated: true)
주석들은 지워서 올려주세요

2023-07-26 14:41 UTC, juyeong525 commented on OnePiece/OnePiece/Scene/Auth/Login/LoginViewController.swift
>      var eyeButton = UIButton(type: .custom)
let 으로 선언해주세요

2023-07-26 14:41 UTC, juyeong525 commented on OnePiece/OnePiece/Scene/Auth/Login/LoginViewController.swift
>      var loginButton = DefaultButton(title: "로그인", backgroundColor: UIColor(named: "mainColor-1")!, titleColor: UIColor(named: "gray-000")!)
let 으로 선언 해주세요

2023-07-26 14:41 UTC, juyeong525 commented on OnePiece/OnePiece/Scene/Auth/Login/LoginViewController.swift
>      override func viewDidLayoutSubviews() {
viewWillLayoutSubviesw 씁시다

2023-07-26 14:41 UTC, juyeong525 commented on OnePiece/OnePiece/Scene/Auth/Login/LoginViewController.swift
> +            //레이블알림 띄우기
이 코드는 어디감?

2023-07-27 04:08 UTC, juyeong525 approved these changes
LGTM 🤜

2023-07-27 04:09 UTC, cyj513 commented
감사합니다!!

2023-07-27 04:10 UTC, merged